import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import React from "react"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <div className="w-[100vw] h-[20vh] bg-[white] flex justify-center items-center"><h1 className="text-6xl  text-[black]">Navbar</h1></div>
        {children}</body>
    </html>
  )
}
